layout_spectrum: 0.8865294873398166
typography_spectrum: 0.46015834506398234
color:
  lightness: 0.948464819417418
  brandColors:
    - '#F2385A'
    - '#F5A503'
    - '#E9F1DF'
    - '#4AD9D9'
    - '#36B1BF'
  saturation: 0.7349067745815114
  brandStrength: 0.4479691575628032
  rhythmicContrast: 0.4033214561558227
name: albertmartinez
analytics:
  twitter: '@iAlbertM'
github: true
description: 'my creative portfolio for graphic design, web design  & development projects. '
author:
  name: Albert Martinez
  url: 'http://ialbertmartinez.com'
  email: ialbertm@icloud.com
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
content: []
content_rating:
  adult: false
opengraph: {}
title: >-
  iAlbert Martinez | Graphic Design Web Design & Development | Creative
  Portfolio
